import Header from "@/components/Header/Header";
import { Open_Sans } from "next/font/google";
import "../../.next/static/fonts/style.css";
import st from "./layout.module.scss";

const sans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={sans.className}>
      <body className={st.body}>
        <Header />
        <main className={st.main}>{children}</main>
        {/* <Header />
        <main className={st.main}>{children}</main>
        <Footer /> */}
      </body>
    </html>
  );
}
